// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Returns application metadata (name, version, rust_version).
AppInfo appInfo() => RustLib.instance.api.crateApiAppInfo();

/// Process a task via the Rust core engine (legacy).
Future<TaskResponse> processTask({required TaskRequest request}) =>
    RustLib.instance.api.crateApiProcessTask(request: request);

/// Returns all available evidence options.
List<EvidenceOption> evidenceOptions() =>
    RustLib.instance.api.crateApiEvidenceOptions();

/// Returns all production rules (for knowledge-base browsing).
List<RuleView> ruleViews() => RustLib.instance.api.crateApiRuleViews();

/// Runs the forward-chaining diagnosis engine.
Future<DiagnosisResult> diagnoseBlueScreen({
  required DiagnosisRequest request,
}) => RustLib.instance.api.crateApiDiagnoseBlueScreen(request: request);
