// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Unified error model for all Rust-to-Dart error reporting.
///
/// This is the only error type that crosses the FFI boundary.
/// Internal Rust errors are converted to this model in the facade layer.
class AppError implements FrbException {
  /// Stable machine-readable error code (e.g. "invalid_input", "internal")
  final String code;

  /// Developer-facing message; Flutter translates for end users
  final String message;

  /// Optional structured context (JSON or key-value pairs)
  final String? details;

  /// Whether the caller may retry the operation
  final bool retryable;

  const AppError({
    required this.code,
    required this.message,
    this.details,
    required this.retryable,
  });

  @override
  int get hashCode =>
      code.hashCode ^ message.hashCode ^ details.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          details == other.details &&
          retryable == other.retryable;
}
