// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  AppInfo dco_decode_app_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DiagnosisRequest dco_decode_box_autoadd_diagnosis_request(dynamic raw);

  @protected
  TaskRequest dco_decode_box_autoadd_task_request(dynamic raw);

  @protected
  DiagnosisConclusion dco_decode_diagnosis_conclusion(dynamic raw);

  @protected
  DiagnosisRequest dco_decode_diagnosis_request(dynamic raw);

  @protected
  DiagnosisResult dco_decode_diagnosis_result(dynamic raw);

  @protected
  EvidenceOption dco_decode_evidence_option(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DiagnosisConclusion> dco_decode_list_diagnosis_conclusion(dynamic raw);

  @protected
  List<EvidenceOption> dco_decode_list_evidence_option(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RuleTrace> dco_decode_list_rule_trace(dynamic raw);

  @protected
  List<RuleView> dco_decode_list_rule_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RuleTrace dco_decode_rule_trace(dynamic raw);

  @protected
  RuleView dco_decode_rule_view(dynamic raw);

  @protected
  TaskRequest dco_decode_task_request(dynamic raw);

  @protected
  TaskResponse dco_decode_task_response(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DiagnosisRequest sse_decode_box_autoadd_diagnosis_request(
    SseDeserializer deserializer,
  );

  @protected
  TaskRequest sse_decode_box_autoadd_task_request(SseDeserializer deserializer);

  @protected
  DiagnosisConclusion sse_decode_diagnosis_conclusion(
    SseDeserializer deserializer,
  );

  @protected
  DiagnosisRequest sse_decode_diagnosis_request(SseDeserializer deserializer);

  @protected
  DiagnosisResult sse_decode_diagnosis_result(SseDeserializer deserializer);

  @protected
  EvidenceOption sse_decode_evidence_option(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DiagnosisConclusion> sse_decode_list_diagnosis_conclusion(
    SseDeserializer deserializer,
  );

  @protected
  List<EvidenceOption> sse_decode_list_evidence_option(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RuleTrace> sse_decode_list_rule_trace(SseDeserializer deserializer);

  @protected
  List<RuleView> sse_decode_list_rule_view(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RuleTrace sse_decode_rule_trace(SseDeserializer deserializer);

  @protected
  RuleView sse_decode_rule_view(SseDeserializer deserializer);

  @protected
  TaskRequest sse_decode_task_request(SseDeserializer deserializer);

  @protected
  TaskResponse sse_decode_task_response(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_diagnosis_request(
    DiagnosisRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_request(
    TaskRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnosis_conclusion(
    DiagnosisConclusion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnosis_request(
    DiagnosisRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnosis_result(
    DiagnosisResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_evidence_option(
    EvidenceOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_diagnosis_conclusion(
    List<DiagnosisConclusion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_evidence_option(
    List<EvidenceOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rule_trace(
    List<RuleTrace> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rule_view(List<RuleView> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_rule_trace(RuleTrace self, SseSerializer serializer);

  @protected
  void sse_encode_rule_view(RuleView self, SseSerializer serializer);

  @protected
  void sse_encode_task_request(TaskRequest self, SseSerializer serializer);

  @protected
  void sse_encode_task_response(TaskResponse self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
