// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -222960959;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_cw_ai_conductor_2026spring',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  AppInfo crateApiAppInfo();

  Future<DiagnosisResult> crateApiDiagnoseBlueScreen({
    required DiagnosisRequest request,
  });

  List<EvidenceOption> crateApiEvidenceOptions();

  Future<void> crateApiInitApp();

  Future<TaskResponse> crateApiProcessTask({required TaskRequest request});

  List<RuleView> crateApiRuleViews();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  AppInfo crateApiAppInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInfoConstMeta =>
      const TaskConstMeta(debugName: "app_info", argNames: []);

  @override
  Future<DiagnosisResult> crateApiDiagnoseBlueScreen({
    required DiagnosisRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_diagnosis_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_diagnosis_result,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiDiagnoseBlueScreenConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagnoseBlueScreenConstMeta => const TaskConstMeta(
    debugName: "diagnose_blue_screen",
    argNames: ["request"],
  );

  @override
  List<EvidenceOption> crateApiEvidenceOptions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_evidence_option,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEvidenceOptionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEvidenceOptionsConstMeta =>
      const TaskConstMeta(debugName: "evidence_options", argNames: []);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<TaskResponse> crateApiProcessTask({required TaskRequest request}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_task_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_response,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiProcessTaskConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessTaskConstMeta =>
      const TaskConstMeta(debugName: "process_task", argNames: ["request"]);

  @override
  List<RuleView> crateApiRuleViews() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rule_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRuleViewsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuleViewsConstMeta =>
      const TaskConstMeta(debugName: "rule_views", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppError dco_decode_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      details: dco_decode_opt_String(arr[2]),
      retryable: dco_decode_bool(arr[3]),
    );
  }

  @protected
  AppInfo dco_decode_app_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AppInfo(
      name: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      rustVersion: dco_decode_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiagnosisRequest dco_decode_box_autoadd_diagnosis_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_diagnosis_request(raw);
  }

  @protected
  TaskRequest dco_decode_box_autoadd_task_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_request(raw);
  }

  @protected
  DiagnosisConclusion dco_decode_diagnosis_conclusion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DiagnosisConclusion(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      confidence: dco_decode_String(arr[2]),
      severity: dco_decode_String(arr[3]),
      explanation: dco_decode_String(arr[4]),
      recommendations: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  DiagnosisRequest dco_decode_diagnosis_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return DiagnosisRequest(selectedEvidence: dco_decode_list_String(arr[0]));
  }

  @protected
  DiagnosisResult dco_decode_diagnosis_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiagnosisResult(
      conclusions: dco_decode_list_diagnosis_conclusion(arr[0]),
      inferredFacts: dco_decode_list_String(arr[1]),
      traces: dco_decode_list_rule_trace(arr[2]),
      warnings: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  EvidenceOption dco_decode_evidence_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EvidenceOption(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DiagnosisConclusion> dco_decode_list_diagnosis_conclusion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_diagnosis_conclusion).toList();
  }

  @protected
  List<EvidenceOption> dco_decode_list_evidence_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_evidence_option).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RuleTrace> dco_decode_list_rule_trace(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rule_trace).toList();
  }

  @protected
  List<RuleView> dco_decode_list_rule_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rule_view).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RuleTrace dco_decode_rule_trace(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RuleTrace(
      ruleId: dco_decode_String(arr[0]),
      ruleName: dco_decode_String(arr[1]),
      matchedFacts: dco_decode_list_String(arr[2]),
      producedFact: dco_decode_String(arr[3]),
      explanation: dco_decode_String(arr[4]),
    );
  }

  @protected
  RuleView dco_decode_rule_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RuleView(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      premises: dco_decode_list_String(arr[2]),
      conclusion: dco_decode_String(arr[3]),
      confidence: dco_decode_String(arr[4]),
      explanation: dco_decode_String(arr[5]),
    );
  }

  @protected
  TaskRequest dco_decode_task_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TaskRequest(
      id: dco_decode_String(arr[0]),
      payload: dco_decode_String(arr[1]),
      action: dco_decode_String(arr[2]),
    );
  }

  @protected
  TaskResponse dco_decode_task_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TaskResponse(
      taskId: dco_decode_String(arr[0]),
      result: dco_decode_String(arr[1]),
      status: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_details = sse_decode_opt_String(deserializer);
    var var_retryable = sse_decode_bool(deserializer);
    return AppError(
      code: var_code,
      message: var_message,
      details: var_details,
      retryable: var_retryable,
    );
  }

  @protected
  AppInfo sse_decode_app_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_rustVersion = sse_decode_String(deserializer);
    return AppInfo(
      name: var_name,
      version: var_version,
      rustVersion: var_rustVersion,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiagnosisRequest sse_decode_box_autoadd_diagnosis_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_diagnosis_request(deserializer));
  }

  @protected
  TaskRequest sse_decode_box_autoadd_task_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_request(deserializer));
  }

  @protected
  DiagnosisConclusion sse_decode_diagnosis_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_confidence = sse_decode_String(deserializer);
    var var_severity = sse_decode_String(deserializer);
    var var_explanation = sse_decode_String(deserializer);
    var var_recommendations = sse_decode_list_String(deserializer);
    return DiagnosisConclusion(
      id: var_id,
      title: var_title,
      confidence: var_confidence,
      severity: var_severity,
      explanation: var_explanation,
      recommendations: var_recommendations,
    );
  }

  @protected
  DiagnosisRequest sse_decode_diagnosis_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_selectedEvidence = sse_decode_list_String(deserializer);
    return DiagnosisRequest(selectedEvidence: var_selectedEvidence);
  }

  @protected
  DiagnosisResult sse_decode_diagnosis_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_conclusions = sse_decode_list_diagnosis_conclusion(deserializer);
    var var_inferredFacts = sse_decode_list_String(deserializer);
    var var_traces = sse_decode_list_rule_trace(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return DiagnosisResult(
      conclusions: var_conclusions,
      inferredFacts: var_inferredFacts,
      traces: var_traces,
      warnings: var_warnings,
    );
  }

  @protected
  EvidenceOption sse_decode_evidence_option(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return EvidenceOption(
      id: var_id,
      label: var_label,
      category: var_category,
      description: var_description,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiagnosisConclusion> sse_decode_list_diagnosis_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiagnosisConclusion>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_diagnosis_conclusion(deserializer));
    }
    return ans_;
  }

  @protected
  List<EvidenceOption> sse_decode_list_evidence_option(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EvidenceOption>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_evidence_option(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RuleTrace> sse_decode_list_rule_trace(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RuleTrace>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rule_trace(deserializer));
    }
    return ans_;
  }

  @protected
  List<RuleView> sse_decode_list_rule_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RuleView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rule_view(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RuleTrace sse_decode_rule_trace(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ruleId = sse_decode_String(deserializer);
    var var_ruleName = sse_decode_String(deserializer);
    var var_matchedFacts = sse_decode_list_String(deserializer);
    var var_producedFact = sse_decode_String(deserializer);
    var var_explanation = sse_decode_String(deserializer);
    return RuleTrace(
      ruleId: var_ruleId,
      ruleName: var_ruleName,
      matchedFacts: var_matchedFacts,
      producedFact: var_producedFact,
      explanation: var_explanation,
    );
  }

  @protected
  RuleView sse_decode_rule_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_premises = sse_decode_list_String(deserializer);
    var var_conclusion = sse_decode_String(deserializer);
    var var_confidence = sse_decode_String(deserializer);
    var var_explanation = sse_decode_String(deserializer);
    return RuleView(
      id: var_id,
      name: var_name,
      premises: var_premises,
      conclusion: var_conclusion,
      confidence: var_confidence,
      explanation: var_explanation,
    );
  }

  @protected
  TaskRequest sse_decode_task_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_payload = sse_decode_String(deserializer);
    var var_action = sse_decode_String(deserializer);
    return TaskRequest(id: var_id, payload: var_payload, action: var_action);
  }

  @protected
  TaskResponse sse_decode_task_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_taskId = sse_decode_String(deserializer);
    var var_result = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return TaskResponse(
      taskId: var_taskId,
      result: var_result,
      status: var_status,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.details, serializer);
    sse_encode_bool(self.retryable, serializer);
  }

  @protected
  void sse_encode_app_info(AppInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.rustVersion, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_diagnosis_request(
    DiagnosisRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_diagnosis_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_request(
    TaskRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_request(self, serializer);
  }

  @protected
  void sse_encode_diagnosis_conclusion(
    DiagnosisConclusion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.confidence, serializer);
    sse_encode_String(self.severity, serializer);
    sse_encode_String(self.explanation, serializer);
    sse_encode_list_String(self.recommendations, serializer);
  }

  @protected
  void sse_encode_diagnosis_request(
    DiagnosisRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.selectedEvidence, serializer);
  }

  @protected
  void sse_encode_diagnosis_result(
    DiagnosisResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_diagnosis_conclusion(self.conclusions, serializer);
    sse_encode_list_String(self.inferredFacts, serializer);
    sse_encode_list_rule_trace(self.traces, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_evidence_option(
    EvidenceOption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_diagnosis_conclusion(
    List<DiagnosisConclusion> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_diagnosis_conclusion(item, serializer);
    }
  }

  @protected
  void sse_encode_list_evidence_option(
    List<EvidenceOption> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_evidence_option(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rule_trace(
    List<RuleTrace> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rule_trace(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rule_view(
    List<RuleView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rule_view(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_rule_trace(RuleTrace self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ruleId, serializer);
    sse_encode_String(self.ruleName, serializer);
    sse_encode_list_String(self.matchedFacts, serializer);
    sse_encode_String(self.producedFact, serializer);
    sse_encode_String(self.explanation, serializer);
  }

  @protected
  void sse_encode_rule_view(RuleView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.premises, serializer);
    sse_encode_String(self.conclusion, serializer);
    sse_encode_String(self.confidence, serializer);
    sse_encode_String(self.explanation, serializer);
  }

  @protected
  void sse_encode_task_request(TaskRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.payload, serializer);
    sse_encode_String(self.action, serializer);
  }

  @protected
  void sse_encode_task_response(TaskResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.taskId, serializer);
    sse_encode_String(self.result, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
