// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Application metadata returned by `app_info()`.
class AppInfo {
  final String name;
  final String version;
  final String rustVersion;

  const AppInfo({
    required this.name,
    required this.version,
    required this.rustVersion,
  });

  @override
  int get hashCode => name.hashCode ^ version.hashCode ^ rustVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version &&
          rustVersion == other.rustVersion;
}

/// A single diagnosis conclusion for a cause.
class DiagnosisConclusion {
  /// Cause fact ID (e.g. "cause:driver_conflict").
  final String id;

  /// Human-readable title (e.g. "驱动冲突/驱动损坏").
  final String title;

  /// Confidence level: "high", "medium", "low".
  final String confidence;

  /// Severity: "critical", "warning", "info".
  final String severity;

  /// Natural-language explanation including inference chain.
  final String explanation;

  /// Recommended actions.
  final List<String> recommendations;

  const DiagnosisConclusion({
    required this.id,
    required this.title,
    required this.confidence,
    required this.severity,
    required this.explanation,
    required this.recommendations,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      confidence.hashCode ^
      severity.hashCode ^
      explanation.hashCode ^
      recommendations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosisConclusion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          confidence == other.confidence &&
          severity == other.severity &&
          explanation == other.explanation &&
          recommendations == other.recommendations;
}

/// User's diagnosis request — just the list of selected evidence IDs.
class DiagnosisRequest {
  final List<String> selectedEvidence;

  const DiagnosisRequest({required this.selectedEvidence});

  @override
  int get hashCode => selectedEvidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosisRequest &&
          runtimeType == other.runtimeType &&
          selectedEvidence == other.selectedEvidence;
}

/// Full diagnosis result returned to Flutter.
class DiagnosisResult {
  /// Diagnosed causes.
  final List<DiagnosisConclusion> conclusions;

  /// All facts inferred during reasoning (excluding original evidence and causes).
  final List<String> inferredFacts;

  /// Complete firing trace for explanation.
  final List<RuleTrace> traces;

  /// Edge-case warnings (no match, weak evidence, conflicts).
  final List<String> warnings;

  const DiagnosisResult({
    required this.conclusions,
    required this.inferredFacts,
    required this.traces,
    required this.warnings,
  });

  @override
  int get hashCode =>
      conclusions.hashCode ^
      inferredFacts.hashCode ^
      traces.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosisResult &&
          runtimeType == other.runtimeType &&
          conclusions == other.conclusions &&
          inferredFacts == other.inferredFacts &&
          traces == other.traces &&
          warnings == other.warnings;
}

/// An evidence option presented to the user in the UI.
class EvidenceOption {
  /// Stable identifier used as a fact literal (e.g. "bugcheck:0xD1").
  final String id;

  /// Display label shown in the UI.
  final String label;

  /// Category for grouping (e.g. "蓝屏代码", "崩溃场景").
  final String category;

  /// Longer description / tooltip.
  final String description;

  const EvidenceOption({
    required this.id,
    required this.label,
    required this.category,
    required this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ category.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvidenceOption &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          category == other.category &&
          description == other.description;
}

/// Trace record of a single rule firing.
class RuleTrace {
  final String ruleId;
  final String ruleName;
  final List<String> matchedFacts;
  final String producedFact;
  final String explanation;

  const RuleTrace({
    required this.ruleId,
    required this.ruleName,
    required this.matchedFacts,
    required this.producedFact,
    required this.explanation,
  });

  @override
  int get hashCode =>
      ruleId.hashCode ^
      ruleName.hashCode ^
      matchedFacts.hashCode ^
      producedFact.hashCode ^
      explanation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleTrace &&
          runtimeType == other.runtimeType &&
          ruleId == other.ruleId &&
          ruleName == other.ruleName &&
          matchedFacts == other.matchedFacts &&
          producedFact == other.producedFact &&
          explanation == other.explanation;
}

/// Read-only view of a production rule (for knowledge-base browsing in UI).
class RuleView {
  final String id;
  final String name;
  final List<String> premises;
  final String conclusion;
  final String confidence;
  final String explanation;

  const RuleView({
    required this.id,
    required this.name,
    required this.premises,
    required this.conclusion,
    required this.confidence,
    required this.explanation,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      premises.hashCode ^
      conclusion.hashCode ^
      confidence.hashCode ^
      explanation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          premises == other.premises &&
          conclusion == other.conclusion &&
          confidence == other.confidence &&
          explanation == other.explanation;
}

/// A task submitted from Flutter to the Rust core for processing.
class TaskRequest {
  final String id;
  final String payload;
  final String action;

  const TaskRequest({
    required this.id,
    required this.payload,
    required this.action,
  });

  @override
  int get hashCode => id.hashCode ^ payload.hashCode ^ action.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskRequest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          payload == other.payload &&
          action == other.action;
}

/// Result of processing a `TaskRequest`.
class TaskResponse {
  final String taskId;
  final String result;
  final String status;

  const TaskResponse({
    required this.taskId,
    required this.result,
    required this.status,
  });

  @override
  int get hashCode => taskId.hashCode ^ result.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskResponse &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          result == other.result &&
          status == other.status;
}
